### ISSUE TITLE
Cannot read property "remove" of undefined when removing a blocked time

### ISSUE THREAD

**Issue by Coteh** [iam4722202468/GuelphScheduler2#4]
I noticed that if you add a blocked time then immediately attempt to delete it, you'll receive the following error (in Chrome):
```
Uncaught TypeError: Cannot read property 'remove' of undefined
    at app.bundle.js:220
    at HTMLDivElement.C (app.bundle.js:220)
    at HTMLDivElement.dispatch (app.bundle.js:39)
    at HTMLDivElement.g.handle (app.bundle.js:39)
```
In Firefox, the error is displayed like the following (but same source line):
```
TypeError: Y[e] is undefined app.bundle.js:220:185527
    C https://guelph.scheduler.online/app.bundle.js:220
    C https://guelph.scheduler.online/app.bundle.js:220
    dispatch https://guelph.scheduler.online/app.bundle.js:39
    handle https://guelph.scheduler.online/app.bundle.js:39
```

Seems like the source lines referenced in the stack trace are pointing to the transpiled source for jQuery UI Effects Size and Sizzle CSS Selector Engine respectively.

It seems like if you either click Play, or you change one of the options for the blocked time (day of week, start/end time of the blocked time), you'll then be able to remove the blocked time without any issues. If the same issue comes up even after changing one of the options, then keep changing one of the options for the blocked time until it can be deleted.

**Comment by iam4722202468** [comment]
Nice catch! I think I've fixed this, if you can't recreate this bug let me know and I'll close this ticket.

**Comment by Coteh** [comment]
Repeatedly added and deleted blocked time on Firefox, Safari, and Chrome. Looks like it's fixed.
